"""
Updates data/film_dashboard.csv with the results of the three enrichment agents (IMDb rating,
Rotten Tomatoes score, mood + reason). Used by the update-cinema skill — not meant to be run by
hand, though you can for debugging.

Each of the three inputs is a text file with one line per movie, EXACTLY in the format the three
agents return:
  --imdb: lines "Title (Year): rating"           e.g. "Inception (2010): 8.8"
  --rt:   lines "Title (Year): percentage%"        e.g. "Inception (2010): 87%"
  --mood: lines "Title (Year): Mood — reason"

Lines from these files are matched to rows of data/film_dashboard.csv by title+year, ignoring
case and punctuation (so small formatting differences between what the agent writes and what's
in the CSV don't break the match).

Only updates the rows whose title+year is found in these files; every other row of the CSV is
left untouched. Adds the rotten_tomatoes and mood_reason columns if they don't already exist
(happens if the CSV was generated by an older version of build_dashboard.py).

Usage:
    python scripts/merge_enrichment.py --imdb imdb.txt --rt rt.txt --mood mood.txt
"""

import argparse
import csv
import re
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"
CSV_PATH = DATA / "film_dashboard.csv"

LINE_RE = re.compile(r"^\s*(.+?)\s\((\d{4})\)\s*:\s*(.+?)\s*$")
MOOD_SEPARATORS = (" — ", " - ", "—", "-")


def norm(s):
    return re.sub(r"[^a-z0-9]", "", s.lower())


def parse_lines(path):
    result = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = LINE_RE.match(line)
            if not m:
                continue
            title, year, value = m.groups()
            result[(norm(title), int(year))] = value
    return result


def parse_mood_value(value):
    for sep in MOOD_SEPARATORS:
        if sep in value:
            mood, _, reason = value.partition(sep)
            return mood.strip(), reason.strip()
    return value.strip(), ""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--imdb", required=True, help="text file with IMDb ratings")
    parser.add_argument("--rt", required=True, help="text file with Rotten Tomatoes scores")
    parser.add_argument("--mood", required=True, help="text file with mood + reason")
    args = parser.parse_args()

    imdb = parse_lines(args.imdb)
    rt = parse_lines(args.rt)
    mood = {k: parse_mood_value(v) for k, v in parse_lines(args.mood).items()}

    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames)
        rows = list(reader)

    for col in ("rotten_tomatoes", "mood_reason"):
        if col not in fieldnames:
            fieldnames.append(col)
        for row in rows:
            row.setdefault(col, "")

    updated = 0
    all_keys_seen = set(imdb) | set(rt) | set(mood)
    matched_keys = set()
    for row in rows:
        if not row.get("year"):
            continue
        key = (norm(row["title"]), int(row["year"]))
        touched = False
        if key in imdb:
            row["imdb_rating"] = imdb[key]
            touched = True
        if key in rt:
            row["rotten_tomatoes"] = rt[key].rstrip("%")
            touched = True
        if key in mood:
            row["mood"], row["mood_reason"] = mood[key]
            touched = True
        if touched:
            updated += 1
            matched_keys.add(key)

    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Updated {updated} rows in {CSV_PATH.name}.")
    unmatched = all_keys_seen - matched_keys
    if unmatched:
        print(f"Warning: {len(unmatched)} movies returned by the agents did not find an exact "
              f"match in the CSV (slightly different title or year?).")


if __name__ == "__main__":
    sys.exit(main())
